# Generated by Django 6.0.4 on 2026-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbooksmodel',
            name='category',
        ),
        migrations.AlterField(
            model_name='addbooksmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='addbooksmodel',
            name='category',
            field=models.ManyToManyField(to='category.categorymodel'),
        ),
    ]
