# Generated by Django 6.0.4 on 2026-05-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_addbooksmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbooksmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
