# Generated by Django 6.0.4 on 2026-05-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbookmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
