# Generated by Django 6.0.4 on 2026-05-07 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_addbooksmodel_price'),
        ('borrow', '0002_borrowbookmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbookmodel',
            name='book',
        ),
        migrations.AddField(
            model_name='borrowbookmodel',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.addbooksmodel'),
        ),
    ]
