# Generated by Django 6.0.4 on 2026-05-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_remove_borrowbookmodel_book_borrowbookmodel_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbookmodel',
            name='orginal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
