# Generated by Django 6.0.4 on 2026-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='department',
        ),
        migrations.AddField(
            model_name='registermodel',
            name='department',
            field=models.ManyToManyField(to='userAuth.departmentmodel'),
        ),
    ]
