# Generated by Django 6.0.4 on 2026-05-06 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_remove_registermodel_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='department',
        ),
        migrations.AddField(
            model_name='registermodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuth.departmentmodel'),
        ),
    ]
