# Generated by Django 6.0.4 on 2026-05-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_remove_registermodel_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('CE', 'CE'), ('BBA', 'BBA'), ('LAW', 'LAW'), ('ENGLISH', 'ENGLISH')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='DepartmentModel',
        ),
    ]
